apiVersion: v1
kind: Service
metadata:
  name: transit-api-service
spec:
  selector:
    app: transit-api
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transit-api
spec:
  selector:
    matchLabels:
      app: transit-api
  replicas: 2
  template:
    metadata:
      labels:
        app: transit-api
    spec:
      containers:
        - name: transit-api
          image: nikitany/transit-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
